// Auto-generated. Do not edit!

// (in-package clean_avoidance.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CleanAvoidanceResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.result_x = null;
      this.result_y = null;
    }
    else {
      if (initObj.hasOwnProperty('result_x')) {
        this.result_x = initObj.result_x
      }
      else {
        this.result_x = 0.0;
      }
      if (initObj.hasOwnProperty('result_y')) {
        this.result_y = initObj.result_y
      }
      else {
        this.result_y = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CleanAvoidanceResult
    // Serialize message field [result_x]
    bufferOffset = _serializer.float64(obj.result_x, buffer, bufferOffset);
    // Serialize message field [result_y]
    bufferOffset = _serializer.float64(obj.result_y, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CleanAvoidanceResult
    let len;
    let data = new CleanAvoidanceResult(null);
    // Deserialize message field [result_x]
    data.result_x = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [result_y]
    data.result_y = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 16;
  }

  static datatype() {
    // Returns string type for a message object
    return 'clean_avoidance/CleanAvoidanceResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'fe56f01890c8a9edde3f6efd85780c31';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    float64 result_x
    float64 result_y
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CleanAvoidanceResult(null);
    if (msg.result_x !== undefined) {
      resolved.result_x = msg.result_x;
    }
    else {
      resolved.result_x = 0.0
    }

    if (msg.result_y !== undefined) {
      resolved.result_y = msg.result_y;
    }
    else {
      resolved.result_y = 0.0
    }

    return resolved;
    }
};

module.exports = CleanAvoidanceResult;
