# request
int8 ADD_LINE=0
int8 DELETE_LINES=1
int8 GET_LINES=2

int8 type
string map_name
uint32[] id
inspur_msgs/Line2DFlt32 line_data
---
# response
uint32 result
string map_name
uint32[] id
float32[] start_x
float32[] start_y
float32[] end_x
float32[] end_y