// Generated by gencpp from file clean_avoidance/CleanAvoidanceResult.msg
// DO NOT EDIT!


#ifndef CLEAN_AVOIDANCE_MESSAGE_CLEANAVOIDANCERESULT_H
#define CLEAN_AVOIDANCE_MESSAGE_CLEANAVOIDANCERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clean_avoidance
{
template <class ContainerAllocator>
struct CleanAvoidanceResult_
{
  typedef CleanAvoidanceResult_<ContainerAllocator> Type;

  CleanAvoidanceResult_()
    : result_x(0.0)
    , result_y(0.0)  {
    }
  CleanAvoidanceResult_(const ContainerAllocator& _alloc)
    : result_x(0.0)
    , result_y(0.0)  {
  (void)_alloc;
    }



   typedef double _result_x_type;
  _result_x_type result_x;

   typedef double _result_y_type;
  _result_y_type result_y;





  typedef boost::shared_ptr< ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator> const> ConstPtr;

}; // struct CleanAvoidanceResult_

typedef ::clean_avoidance::CleanAvoidanceResult_<std::allocator<void> > CleanAvoidanceResult;

typedef boost::shared_ptr< ::clean_avoidance::CleanAvoidanceResult > CleanAvoidanceResultPtr;
typedef boost::shared_ptr< ::clean_avoidance::CleanAvoidanceResult const> CleanAvoidanceResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator1> & lhs, const ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator2> & rhs)
{
  return lhs.result_x == rhs.result_x &&
    lhs.result_y == rhs.result_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator1> & lhs, const ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace clean_avoidance

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe56f01890c8a9edde3f6efd85780c31";
  }

  static const char* value(const ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe56f01890c8a9edULL;
  static const uint64_t static_value2 = 0xde3f6efd85780c31ULL;
};

template<class ContainerAllocator>
struct DataType< ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clean_avoidance/CleanAvoidanceResult";
  }

  static const char* value(const ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"float64 result_x\n"
"float64 result_y\n"
;
  }

  static const char* value(const ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result_x);
      stream.next(m.result_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CleanAvoidanceResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clean_avoidance::CleanAvoidanceResult_<ContainerAllocator>& v)
  {
    s << indent << "result_x: ";
    Printer<double>::stream(s, indent + "  ", v.result_x);
    s << indent << "result_y: ";
    Printer<double>::stream(s, indent + "  ", v.result_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLEAN_AVOIDANCE_MESSAGE_CLEANAVOIDANCERESULT_H
