// Generated by gencpp from file clean_avoidance/CleanAvoidanceActionGoal.msg
// DO NOT EDIT!


#ifndef CLEAN_AVOIDANCE_MESSAGE_CLEANAVOIDANCEACTIONGOAL_H
#define CLEAN_AVOIDANCE_MESSAGE_CLEANAVOIDANCEACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <clean_avoidance/CleanAvoidanceGoal.h>

namespace clean_avoidance
{
template <class ContainerAllocator>
struct CleanAvoidanceActionGoal_
{
  typedef CleanAvoidanceActionGoal_<ContainerAllocator> Type;

  CleanAvoidanceActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  CleanAvoidanceActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::clean_avoidance::CleanAvoidanceGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CleanAvoidanceActionGoal_

typedef ::clean_avoidance::CleanAvoidanceActionGoal_<std::allocator<void> > CleanAvoidanceActionGoal;

typedef boost::shared_ptr< ::clean_avoidance::CleanAvoidanceActionGoal > CleanAvoidanceActionGoalPtr;
typedef boost::shared_ptr< ::clean_avoidance::CleanAvoidanceActionGoal const> CleanAvoidanceActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator1> & lhs, const ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator1> & lhs, const ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace clean_avoidance

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cdfd538d259515a2d7e1f0b7cdd0a704";
  }

  static const char* value(const ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcdfd538d259515a2ULL;
  static const uint64_t static_value2 = 0xd7e1f0b7cdd0a704ULL;
};

template<class ContainerAllocator>
struct DataType< ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clean_avoidance/CleanAvoidanceActionGoal";
  }

  static const char* value(const ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"CleanAvoidanceGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: clean_avoidance/CleanAvoidanceGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"float64 goal_x\n"
"float64 goal_y\n"
;
  }

  static const char* value(const ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CleanAvoidanceActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clean_avoidance::CleanAvoidanceActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::clean_avoidance::CleanAvoidanceGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLEAN_AVOIDANCE_MESSAGE_CLEANAVOIDANCEACTIONGOAL_H
