(cl:defpackage clean_avoidance-msg
  (:use )
  (:export
   "<CLEANAVOIDANCEACTION>"
   "CLEANAVOIDANCEACTION"
   "<CLEANAVOIDANCEACTIONFEEDBACK>"
   "CLEANAVOIDANCEACTIONFEEDBACK"
   "<CLEANAVOIDANCEACTIONGOAL>"
   "CLEANAVOIDANCEACTIONGOAL"
   "<CLEANAVOIDANCEACTIONRESULT>"
   "CLEANAVOIDANCEACTIONRESULT"
   "<CLEANAVOIDANCEFEEDBACK>"
   "CLEANAVOIDANCEFEEDBACK"
   "<CLEANAVOIDANCEGOAL>"
   "CLEANAVOIDANCEGOAL"
   "<CLEANAVOIDANCERESULT>"
   "CLEANAVOIDANCERESULT"
  ))

